spring.application.name=RideFlow
# Supabase DB (set SESSION POOLER URL if your network is IPv4-only)
spring.datasource.url=jdbc:postgresql://db.bzwlcxscoixtytqhmihr.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Aliakbar786$
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.connect-retries=12
spring.flyway.connect-retries-interval=5s


#secret key for admin
admin.secret=Ride_Flow_admin_Super123456